# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - id: "cli-amd64"
    env:
      - CGO_ENABLED=0
    main: ./cmd/schemalex-deploy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    binary: schemalex-deploy
    ldflags:
      - -s -w
      - -X github.com/shogo82148/schemalex-deploy.version={{.Version}}
  - id: "cli-arm64"
    env:
      - CGO_ENABLED=0
    main: ./cmd/schemalex-deploy
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
    binary: schemalex-deploy
    ldflags:
      - -s -w
      - -X github.com/shogo82148/schemalex-deploy.Version={{.Version}}
archives:
  - builds:
      - cli-amd64
      - cli-arm64
    name_template: "schemalex-deploy_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

nfpms:
  - id: package-amd64
    builds:
      - cli-amd64
    package_name: schemalex-deploy
    homepage: https://github.com/shogo82148/schemalex-deploy/
    maintainer: Ichinose Shogo <shogo82148@gmail.com>
    description: Schema management tool for MySQL
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin
  - id: package-arm64
    builds:
      - cli-arm64
    package_name: schemalex-deploy
    homepage: https://github.com/shogo82148/schemalex-deploy/
    maintainer: Ichinose Shogo <shogo82148@gmail.com>
    description: Schema management tool for MySQL
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    release: 1
    epoch: 0
    bindir: /usr/bin

# TODO: publish rpm packages
# blobs:
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-amd64]
#     folder: amazonlinux/2/x86_64/schemalex-deploy
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-arm64]
#     folder: amazonlinux/2/aarch64/schemalex-deploy
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-amd64]
#     folder: centos/7/x86_64/schemalex-deploy
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-arm64]
#     folder: centos/7/aarch64/schemalex-deploy
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-amd64]
#     folder: centos/8/x86_64/schemalex-deploy
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-arm64]
#     folder: centos/8/aarch64/schemalex-deploy
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-amd64]
#     folder: almalinux/8/x86_64/schemalex-deploy
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-arm64]
#     folder: almalinux/8/aarch64/schemalex-deploy
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-amd64]
#     folder: rockylinux/8/x86_64/schemalex-deploy
#   - provider: s3
#     bucket: shogo82148-rpm-temporary
#     ids: [package-arm64]
#     folder: rockylinux/8/aarch64/schemalex-deploy

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
