name: reviewdog
on: [pull_request]
jobs:

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - uses: actions/cache@v2
        with:
          path: |
              ~/.cache/go-build
              ~/go/pkg/mod
              ~/go/pkg/mod
          key: ${{ runner.os }}-golangcilint-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golangcilint-

      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          reporter: "github-pr-review"
          level: warning

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: "github-pr-review"
          level: warning
