name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SCHEMALEX_DATABASE_HOST: "127.0.0.1"
  SCHEMALEX_DATABASE_PORT: "3306"
  SCHEMALEX_DATABASE_USER: "root"
  SCHEMALEX_DATABASE_PASSWORD: "verysecret"

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go:
          - "1.16"
        mysql:
          - '8.0'
          - '5.7'
          - '5.6'
          - 'mariadb-10.6'
          - 'mariadb-10.5'
          - 'mariadb-10.4'
          - 'mariadb-10.3'

    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: restore cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: ${{ matrix.mysql }}
          user: ${{ env.SCHEMALEX_DATABASE_USER }}
          password: ${{ env.SCHEMALEX_DATABASE_PASSWORD }}

      - name: Test
        run: make test
        shell: bash

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: Go-${{ matrix.go }}-OS-${{ matrix.os }}-MYSQL-${{ matrix.mysql }}
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    if: always()
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - name: Check GoReleaser configure
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: check

  check-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Before script
        run: |
          go install golang.org/x/tools/cmd/stringer@latest
          make generate
        shell: bash
      - name: Diff check
        run: make check-diff
        shell: bash
